### ISSUE TITLE
.net 6.0 IOS target

### ISSUE THREAD

**Issue by jona-1993** [oxyplot/oxyplot-xamarin#122]
Hello,

We would like migrate own project with .net 6 ios. But the package "OxyPlot.Xamarin.iOS" doesn't work. 
We can't install de package.

NU1202: Package OxyPlot.Xamarin.iOS 1.1.0-unstable0011 is not compatible with net6.0-ios15.2 (.NETCoreApp,Version=v6.0). OxyPlot.Xamarin.iOS 1.1.0-unstable0011 package supports: xamarinios10 (Xamarin.iOS,Version=v1.0)

Is it possible to have a "net6.0-ios" target?

**Comment by trinnguyen** [comment]
I've just pushed a new Nuget package for Net 7.0 for iOS, as I need it for the migrated iOS app.

Nuget: https://www.nuget.org/packages/Tnn.OxyPlot.Xamarin.iOS/
Source: https://github.com/trinnguyen/xamarin-bindings/tree/master/OxyPlot.Xamarin.iOS

Try use them while waiting for the team to push new version.

**Comment by onurhazar** [comment]
Hey! Thanks for the package! I installed it but panning/zooming still doesn't work with Oxyplot.Core 2.1.2 in iOS. I have net 7.0 ios project.

**Comment by janusw** [comment]
I'll note that there is a Oxyplot port for Maui now: https://github.com/oxyplot/oxyplot-maui
First packages available here: https://www.nuget.org/packages/OxyPlot.Maui.Skia

Does this work for you guys?
