### ISSUE TITLE
Unable to scroll page when adding OxyPlot to ContentPage

### ISSUE THREAD

**Issue by naveeng2228** [oxyplot/oxyplot-xamarin#61]
### Steps to reproduce

1. Create a cross-platform (Xamarin Pages) project in VS 2015 with 4.0 Framework.
2. Now add multiple charts to your ContentPage. And Add guester listeners to few charts.
3. Now try to launch your app on IOS devices either Iphone or Ipad.
4. Now try to scroll the page.
5. At-least try to perform tap on the charts those are having tap guster listeners.

Platform: Xamarin.Forms
.NET version: 4.0

### Expected behaviour

Page should scroll and can perform tapping operations which are working smooth in Android.

### Actual behaviour

Unable to scroll the page. Or even Can't perform click operations on charts.

**Comment by NeilMalcolm** [comment]
Having this issue also. 

I have a handful of PlotModels in a Grid, which is contained within a scrollview. On Android, this works perfectly well, as said by naveeng2228. But on iOS, Scrolling can only be achieved by interacting with non-oxyplot elements of the UI, such as boxviews, blank spaces, etc.

However, I can interact with PlotModels using TouchStarted, TouchDelta, TouchCompleted..

**Comment by ukhimesra** [comment]
Does anyone has resolution for this problem?

**Comment by nvngogineni** [comment]
Still there is no resolution from OxyPlot Team. But I have temporally solved this issue by overlapping OxyPlotView with a transparent AbsoluteView. I am expect a solution from the OxyPlot Team.

**Comment by erdmenchen** [comment]
@nvngogineni can you show a detailed example of your fix, please?

**Comment by hannesganthaler85** [comment]
The bug still exists. What I did is I overlapped the graph view with a transparent UIView with same width and height to enable scrolling. But I think user interaction with the graph is not possible anymore (like scrolling or selecting graph points) but I do not need this.

**Comment by PavaniTatikonda27** [comment]
Any update on this issue? Do we have any fix. We are also having interactions in graphs.

**Comment by PavaniTatikonda27** [comment]
I fixed this issue by removing the pan zoom Gesture in iOS.

**Comment by chaoyebugao** [comment]
Any progress on this issue?

**Comment by Kistelekig98** [comment]
I still have the issue in Xamarin.iOS. It is quite sad, that we cant scroll when using PlotView since 2017.
